// react-ecommerce/src/App.tsx
import React, { useEffect, useState, useCallback } from "react";
import { useLocalStorage } from "react-use";
import { Switch, Route, useHistory, useLocation } from "react-router-dom";

import "./App.css";

import type { Product } from "./product";
import { HomePage } from "./components/HomePage";
import { ProductDetail } from "./components/ProductDetail";
import { Header } from "./components/Header";
let index = 0;
function App() {
  console.log(`App: ${index++}`);
  const [cart, setCart] = useLocalStorage<Product[]>("cart", []);
  const [products, setProducts] = useState<Product[]>([]);

  const onAddToCart = useCallback(
    (product: Product) => {
      setCart([...(cart ?? []), product]);
    },
    [cart, setCart]
  );

  const onClearCart = useCallback(() => {
    setCart([]);
  }, [setCart]);

  useEffect(() => {
    fetch("http://fakestoreapi.com/products")
      .then((res) => res.json())
      .then(setProducts);
  }, []);

  const history = useHistory();
  const location = useLocation();
  const [search, setSearch] = useState("");
  const onSetSearch = useCallback(
    (search: string) => {
      setSearch(search);
      if (location.pathname !== "/") {
        history.push("/");
      }
    },
    [setSearch, history, location]
  );

  return (
    <div>
      <Header
        cart={cart ?? []}
        onClearCart={onClearCart}
        search={search}
        onSetSearch={onSetSearch}
      />
      <Switch>
        <Route exact path="/">
          <HomePage
            products={products}
            onAddToCart={onAddToCart}
            search={search}
          />
        </Route>
        <Route path="/detail/:id">
          <ProductDetail products={products} onAddToCart={onAddToCart} />
        </Route>
      </Switch>
    </div>
  );
}

export default App;

// solid-ecommerce/src/App.tsx
import { Route, Routes } from 'solid-app-router';
import { Component, createResource, createSignal } from 'solid-js';

import { Header } from './components/Header';
import { HomePage } from './components/HomePage';
import { Product } from './product';

const App: Component = () => {
  const [search, setSearch] = createSignal("");
  const [cart, setCart] = createSignal<Product[]>([]);
  const [products] = createResource<Product[]>(
    async () => {
      const res = await fetch("http://fakestoreapi.com/products");
      return await res.json();
    },
    {
      initialValue: [],
    }
  );
  return (
    <div>
      <Header
        cart={cart}
        onClearCart={() => {
          setCart([]);
        }}
        search={search}
        onSetSearch={(str) => setSearch(str)}
      />
      <Routes>
        <Route
          path="/"
          element={
            <HomePage
              products={products}
              search={search}
              onAddToCart={(p) => setCart([...cart(), p])}
            />
          }
        />
      </Routes>
    </div>
  );
};

export default App;
